ReadMe.md
src/Controllers/CustomValueShow.php

Reverts exceedone/exment#138
Because I want to merge only readme

Revert "Bug fix and support IE to Edge"

---

src/ColumnItems/CustomItem.php
src/Grid/Filter/StartsWith.php
src/Model/CustomTable.php

default search is "query%", 
but set "exment.filter_search_full" is true, search query is "%query%",

Add search query like

---

src/ColumnItems/CustomItem.php
src/Controllers/CustomValueController.php
src/Controllers/CustomValueForm.php
src/Controllers/CustomValueShow.php
src/Controllers/CustomViewController.php
src/Model/CustomTable.php
src/Services/Helpers.php

Issue #287 save prev filter and sort order

---

resources/lang/ja/exment.php
src/Auth/HasPermissions.php
src/Controllers/CustomValueController.php
src/Controllers/CustomValueGrid.php
src/Controllers/CustomValueSummary.php
src/Controllers/CustomViewController.php
src/Controllers/DashboardBoxController.php
src/Controllers/SearchController.php
src/Enums/ViewKindType.php
src/Form/Tools/GridChangeView.php
src/Model/CustomView.php
src/Model/CustomViewFilter.php

Revert "Issue #303: add all data view"

---

public/vendor/exment/js/customscript.js
src/Controllers/CustomValueController.php
src/Web/ts/customscript.ts

Modify script class

---

src/Console/BackupCommand.php

Fix remove old backups

---

.gitignore

add `.gitignore`, enhancement for dev

:+1: Add gitignore

---

src/DataItems/Form/DefaultForm.php

Relationの追加編集を常に行えるように修正。
- リレーションの追加、編集は常に行えてよいのでは？
- 編集時にRead Onlyでないといけない理由は何かありますか？

:bug: Fix bug refs #927

---

src/Model/CustomValue.php

列数が多い場合に下記の処理に時間がかかっていたのでプロパティを利用しました。
```
Exceedone\Exment\Model\CustomValue::getBasicLabel
```
* 元々の挙動に影響がないか

Setting a value to the Label property of the CustomValue class

---

.github/workflows/unittest.yml

The modification of the unit test for SQL Server has been completed and added to the exment side.
I have confirmed that it works with github actions.

Add SQL Server UnitTest

---

src/Model/Notify.php

通知設定で使用する条件ビュー #1126

---

.github/workflows/check-lang.yml
src/Console/CheckLangCommand.php

exment:checklangコマンドをgithub actionsのワークフローに追加しました。
workflowに追加するにあたって重複があった場合にワークフローのジョブをfailさせる必要がありました。
そのため、コマンドのexit codeをfailureで返すため重複がある場合のexit codeを1になるように修正を加えました。

Add exment:checklang command

---

.github/workflows/php-cs-fixer.yml

update PHP-CS-Fixer ver.3

---

src/Controllers/RoleGroupController.php
src/Model/Menu.php
src/Model/ModelBase.php
src/Model/Plugin.php
src/Notifications/MicrosoftTeamsSender.php
src/Notifications/SlackSender.php
src/Services/ReplaceFormat/ReplaceFormatService.php

PHP Stanのエラーを修正いたしました。
お手すきの際にご査収ください。

fix phpstan error

---

src/DataItems/Grid/DefaultGrid.php

bugfix refer parent field from modal list

---

src/Services/DataImportExport/Providers/Import/LoginUserProvider.php

Issue#1227 bugfix for login user import

---

src/Form/Field/RadioButton.php

Issue#1235 bugfix  radiobutton on modal

---

.github/workflows/phpstan.yml
phpstan.neon.dist
src/ColumnItems/CustomColumns/SelectTable.php

fix phpstan

---

resources/views/auth/2factor/2factor-email.blade.php
resources/views/auth/email.blade.php
resources/views/auth/login.blade.php

Closes #1517 
- ログイン関連フォームのinput要素の属性指定

#1517 fix input type input to text

---

.github/workflows/phpstan.yml

phpstan.ymlで使用しているactionのバージョンを更新しました。

update phpstan github actions

---

.github/workflows/check-lang.yml

check-lang.ymlで使用しているactionのバージョンを更新しました。

update check lang actions
